matrix:
  include: 
    - language: node_js
      node_js:
        "lts/*"
      install: 
        - yarn install
      cache: yarn
      script: 
        - yarn lint
        - yarn spellcheck
        - find . -not -path './**/node_modules/*' -name "*.md" | xargs docker run --rm --read-only -v $PWD:/data robertbeal/markdown-link-checker
    - language: csharp
      install: 
        - dotnet restore
        - dotnet tools install --tool-path ./tools/ dotnet-format
      script:
        - dotnet-format --dry-run --check
        - dotnet build
